title: COD DMZ Wiki
description: A wiki for a game that's on life support
theme: just-the-docs

url: https://kyokyoknutt.github.io/dmz-wiki

color_scheme: dark
footer_content: "Copyright &copy; 2024 kyokyoknutt. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

heading_anchors: true

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: yellow
  new:
    title: New!
    color: green

search_enabled: true
search:
  heading-level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  focus_shortcut_key: 'k'

aux_links:
  "Fandom Wiki": https://callofduty.fandom.com/wiki/DMZ
  "GitHub Repo": https://github.com/kyokyoknutt/dmz-wiki
